In [ ]:
import numpy as np

In [ ]:
def printnameNtimes(i,n):
  if i>n:
    return
  else:
    print('Neha')
    printnameNtimes(i+1,n)

printnameNtimes(1,5)

Neha
Neha
Neha
Neha
Neha


In [ ]:
def printNumLin(i,N):
  if i>N:
    return
  else:
    print(i,end=' ')
    printNumLin(i+1,N)


printNumLin(1,3)

1 2 3 

In [ ]:
def printOpposite(i,N):
  if i<1:
    return
  else:
    print(i)
    printOpposite(i-1,N)

printOpposite(3,3)

3
2
1


In [ ]:
def printNum(i,N):
  if i<1:
    return
  else:
    printNum(i-1,N)
    print(i)

printNum(3,3)

1
2
3


In [ ]:
def printNtoOne(i,N):
  if i>N:
    return
  else:
    printNtoOne(i+1,N)
    print(i)

printNtoOne(1,3)

3
2
1


In [ ]:
def summation(i,sum):

  if i<0:
    print(sum)
    return
  else:
    summation(i-1,sum+i)



summation(3,0)

6


In [ ]:
def add(N):
  if N==0:
    return 0
  else:
    return N+add(N-1)

add((3))

6

In [ ]:
def revArray(arr,l,r):
  if l>=r:
    print(arr)
    return
  else:
    save=arr[l]
    arr[l]=arr[r]
    arr[r]=save
    revArray(arr,l+1,r-1)


arr=np.array([1,2,3,4])
revArray(arr,0,len(arr)-1)
arr=np.array([5,4,2,1,8])
revArray(arr,0,len(arr)-1)

[4 3 2 1]
[8 1 2 4 5]


In [ ]:
#2nd method
def revArray2(arr,i):
  if i==len(arr)//2:
    print(arr)
    return
  else:
    save=arr[i]
    arr[i]=arr[len(arr)-i-1]
    arr[len(arr)-i-1]=save
    revArray2(arr,i+1)

arr=np.array([1,2,3,4])
revArray2(arr,0)
arr=np.array([5,4,2,1,8])
revArray2(arr,0)



[4 3 2 1]
[8 1 2 4 5]


In [ ]:
def check_palindrome(s,l,r):
  if l>=r:
    return True
  elif s[l]==s[r]:
    return check_palindrome(s,l+1,r-1)
  else:
    return False

s='malayalam'
check_palindrome(s,0,len(s)-1)


True

In [ ]:
def printsubsets(i,arr,empty_lst):
  if i>=len(arr):
    print(np.array(empty_lst))
    return
  else:
    empty_lst.append(arr[i])
    printsubsets(i+1,arr,empty_lst)
    empty_lst.remove(arr[i])
    printsubsets(i+1,arr,empty_lst)

arr=np.array([3,1,2])
printsubsets(0,arr,[])

[3 1 2]
[3 1]
[3 2]
[3]
[1 2]
[1]
[2]
[]


Print sub-arrays whose summation is equal to sum

In [ ]:
def printSubArrays(i,arr,lst,sum):

  if sum == 2:
    print(lst)
    return
  else:
    lst.append(arr[i])
    printSubArrays(i+1,arr,lst,sum+arr[i])
    lst.remove(arr[i])
    printSubArrays(i+1,arr,lst,sum-arr[i])

arr=np.array([1,2,1])
printSubArrays(0,arr,[],0)

IndexError: ignored

In [ ]:
def remove_char_a(s,out,i):
  if i == len(s):
    print(out)
    return
  elif s[i] != 'a':
    out+=s[i]
  return remove_char_a(s,out,i+1)

remove_char_a('baccad','',0)

bccd


In [ ]:
def startwithApple(s,out):
  x=s.startswith('apple')
  if len(s) == 0:
    return False
  elif x == True:
    return x
  return startwithApple(s[1:],out)

print(startwithApple('dapplefg',''))

True


In [ ]:
def check_sort(arr,i):
  if i == len(arr)-1:
    return 'Sorted'

  elif arr[i] < arr[i+1]:
    return check_sort(arr,i+1)

  else:
    return 'Unsorted'

arr = np.array([1,2,4,6,7])
print(check_sort(arr,0))

Sorted


In [ ]:
def search(arr,i,target):
  if i == len(arr):
    return False
  elif arr[i] == target:
    return True

  return search(arr,i+1,target)

arr = np.array([1,5,7,8,34,2])
print(search(arr,0,2))

True


In [ ]:
def printArray(arr,i,target,lst):
  if i == len(arr):
    print(np.array(lst))
    return

  elif arr[i] == target:
    lst.append(i)
  return printArray(arr,i+1,target,lst)

arr = np.array([1,2,4,4,5])
printArray(arr,0,4,[])

[2 3]



Practice Sheet

In [ ]:
#1
def sumDigits(n):
  sum=0
  if n<10:
    return n
  else:
    sum+=n%10
    return sum+sumDigits(n//10)


print(sumDigits(126))

9


In [ ]:
#2
def bunnyEars(i,n,sum):
  if i>n:
    print(sum)
    return
  elif n==0:
    return 0
  elif i%2==0:
    sum+=3
    return bunnyEars(i+1,n,sum)
  elif i%2!=0:
    sum+=2
    return bunnyEars(i+1,n,sum)

bunnyEars(1,2,0)

5


In [ ]:
#3
def count7(n):
  count=0
  if n



In [ ]:
#4
def check_char(i,string,count):
  if i>=len(string):
    print(count)
    return

  if string[i]=='x':
    count+=1
    return check_char(i+1,string,count)
  else:
    return check_char(i+1,string,count)

check_char(0,'xxhi',0)

2


In [ ]:
#5
def changePi(string,out):
  x=string.startswith('pi')
  if len(string) == 0:
    return out
  elif x == False:
    out+=string[0]
  elif x == True:
    out+='3.14'
    return changePi(string[2:],out)

  return changePi(string[1:],out)


print(changePi('xpix',''))

x3.14x


In [ ]:
#6
def array11(arr,idx,count):
  if idx>=len(arr):
    print(count)
    return
  elif arr[idx]==11:
    count+=1
  return array11(arr,idx+1,count)

arr=np.array([1,2,11])
array11(arr,0,0)

1


In [ ]:
#7
def pairStar(s,out):
  if len(s) == 0:
    print(out)
    return
  elif len(s) == 1:
    out+=s
  elif len(s) > 1:
    if s[0] == s[1]:
      out+=s[0]+'*'
    else:
      out+=s[0]
  else:

    out+=s[0]

  return pairStar(s[1:],out)



pairStar('hello',"")

hel*lo


In [ ]:
#8
def countAbc(s,count):

  if len(s) == 0:
    return count
  elif s.startswith('abc') or s.startswith('aba') :
    count+=1

  return countAbc(s[1:],count)


print(countAbc("abc",0))
print(countAbc("abcxxabc", 0))

1
2


In [ ]:
#9
def countHi2(s,count,out):
  if len(s) == 0:
    return count
  elif s.startswith('hi'):
    if out[len(out)-1] != 'x':
      count += 1
  else:
    out += s[0]
  return countHi2(s[1:],count,out)

print(countHi2("ahixhi", 0, ''))
print(countHi2("ahibhi", 0, ''))

1
2


In [ ]:
#10
def subsetCount(s,sub,count):
  x = s.startswith(sub)
  if len(s) == 0:
    print(count)
    return
  if x == True:
    count+=1
  return subsetCount(s[1:],sub,count)

subsetCount("catcowcat", "cat",0)


2


In [ ]:
#11
def bunnyEars(n):
  if n == 0:
    return 0
  elif n == 1:
    return 2
  else:
    return 2 + bunnyEars(n-1)

print(bunnyEars(3))


6


In [ ]:
#12
def triangle(n):
  if n == 0:
    return 0
  elif n == 1:
    return 1
  else:
    return n + triangle(n-1)

print(triangle(2))

3


In [ ]:
#13
def noX(s,out):
  if len(s) == 0:
    print(out)
    return
  elif s[0] != 'x':
    out += s[0]
  return noX(s[1:],out)

noX("xaxb",'')


ab


In [ ]:
#14



In [ ]:
#15
def endX(s,out1,out2):
  if len(s) == 0:
    return out1+out2

  elif s[0] != 'x':
    out1+=s[0]
  elif s[0] == 'x':
    out2+=s[0]
  return endX(s[1:],out1,out2)

print(endX("xxre",'',''))

rexx


In [ ]:
#16
def count11(s,out,count):
  if len(s) == 0:
    return count
  elif s.startswith('11'):
    if out[len(out)-1] != '1':
      count += 1
  else:
    out += s[0]
  return count11(s[1:], out, count)

print(count11("11abc11", ' ', 0))
print(count11("abc11x11x11", ' ', 0))

2
3


In [ ]:
#17
def parenBit(s,out):



print("xyz(abc)123", '')

xyz(abc)123 


In [ ]:
#18
def strCopies(s,sub,num,count):
  x = s.startswith(sub)
  if len(s) == 0:
    if count == num:
      return True
    else:
      return False
  elif x :
    count += 1
  return strCopies(s[1:],sub,num,count)

print(strCopies("catcowcat", "cat", 2, 0))
print(strCopies("catcowcat", "cow", 2, 0))

True
False


In [ ]:
#19
def changeX(s,out):
  if len(s) == 0:
    return out
  elif s[0] == 'x':
    out += 'y'
  else:
    out += s[0]
  return changeX(s[1:],out)

print(changeX("codex",''))

codey


In [ ]:
#20
def array6(arr,i):
  if i == len(arr):
    return False
  elif arr[i] == 6:
    return True
  return array6(arr,i+1)

print(array6([1, 6, 4], 0))

True


In [ ]:
#21
def allStar(s,i,out):
  if i == len(s):
    return out
  else:
    if i != len(arr)-1:
      out = out + s[i] + '*'
    else:
      out = out + s[i]
  return allStar(s, i+1, out)

print(allStar("hello",0,''))

h*e*l*l*o


In [ ]:
#22
